apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: JAVA_TOOL_OPTIONS
          {{- $max := 15 | sub ((100 | div ((.Values.resources.limits.memory | replace "Mi" "" | mul 95 | int)))) -}}
          {{- $initial := 15 | sub (( .Values.resources.requests.memory | replace "Mi" "" | int)) -}}
          {{- if gt $initial $max }}
          value: "-Xmx{{ $max }}m -Xms{{ $max }}m"
          {{- else }}
          value: "-Xmx{{ $max }}m -Xms{{ $initial }}m"
          {{- end }}
        - name: KAFKA_HOST
          value: {{ .Values.env.kafkaHost }}
#       - name: A_SECRET
#         valueFrom:
#           secretKeyRef:
#            name: sec-ktor-auth0-permissions-ktor-auth0-permissions-key
#            key: secretKey
        resources:
{{ toYaml .Values.resources | indent 12 }}
